version: 1.0

.common_params: &common_params
  resolve_s3: true
  region: 'eu-central-1'
  confirm_changeset: 'true'
  capabilities: 'CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM'
  image_repositories: []

test:
  deploy:
    parameters:
      <<: *common_params
      s3_prefix: 'test-flutter-aws-push-notification'
      stack_name: 'test-flutter-aws-push-notification'
      parameter_overrides:
        - Env="test"
        - ProjectName="test-flutter-aws-push-notification"
        - UserPoolDomainName="test-flutter-aws-push-notification"
        - UserPoolName="test-flutter-aws-push-notification"
        - PushNotificationPlatformArn="arn:aws:sns:eu-central-1:735523598888:app/GCM/test-push-notification"
      tags:
        - 'Environment=test'
        - 'ProjectName=test-flutter-aws-push-notification'
