AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Flutter appointement backend'
Globals:
  Function:
    Timeout: 30
Parameters:
  ProjectName:
    Type: String
  Env:
    Type: String
    Description: dev|test|prod
  UserPoolDomainName:
    Type: String
    Description: Domain name for user pool
  UserPoolName:
    Type: String
    Description: User pool name
  PushNotificationPlatformArn:
    Type: String

Resources:

  SQS:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./iac/sqs.yaml
      Parameters:
        Env: !Ref Env
        PushNotificationName: !GetAtt DynamoDB.Outputs.PushNotificationName
        PushNotificationTokenName: !GetAtt DynamoDB.Outputs.PushNotificationTokenName
        PushNotificationPlatformArn: !Ref PushNotificationPlatformArn
  
  DynamoDB:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./iac/dynamodb.yaml
      Parameters:
        Env: !Ref Env

